data_cleaning:
  convert_dtypes: true
  fill_categorical_with: mode
  fill_numeric_with: mean
  handle_outliers: true
  log_changes: true
  outlier_threshold: 3.0
  remove_columns_with_missing_threshold: 0.4
  remove_duplicates: true
supervisor:
  max_concurrent_agents: 3
  retry_attempts: 2
  timeout_seconds: 300
