# Otto Semantic Compression - Konfiguration
# ========================================

# Komprimierung-Einstellungen
compression:
  # Zeit bis zur Komprimierung (in Stunden)
  threshold_hours: 24
  
  # Minimale Anzahl Erinnerungen für Cluster
  min_cluster_size: 2
  
  # Maximale Anzahl Erinnerungen im Speicher
  max_memories: 1000
  
  # Komprimierungs-Interval (in Sekunden)
  interval_seconds: 86400  # 24 Stunden

# Semantische Cluster-Definitionen
clusters:
  arbeit:
    keywords: ['task', 'projekt', 'deadline', 'meeting', 'arbeit', 'job', 'beruf']
    description: "Arbeitsbezogene Erinnerungen"
    
  emotion:
    keywords: ['gefühle', 'stimmung', 'frust', 'freude', 'traurig', 'glücklich', 'wütend']
    description: "Emotionale Erinnerungen"
    
  technik:
    keywords: ['computer', 'software', 'hardware', 'bug', 'programm', 'code', 'system']
    description: "Technische Erinnerungen"
    
  gesundheit:
    keywords: ['körper', 'müdigkeit', 'energie', 'wohlbefinden', 'krank', 'fit', 'schlaf']
    description: "Gesundheitsbezogene Erinnerungen"
    
  sozial:
    keywords: ['freunde', 'familie', 'kommunikation', 'beziehung', 'treffen', 'gespräch']
    description: "Soziale Interaktionen"
    
  lernen:
    keywords: ['wissen', 'verstehen', 'studieren', 'entwicklung', 'lernen', 'bildung']
    description: "Lern- und Entwicklungsprozesse"
    
  kreativ:
    keywords: ['idee', 'kreativ', 'inspiration', 'kunst', 'musik', 'schreiben', 'design']
    description: "Kreative Prozesse"
    
  alltag:
    keywords: ['essen', 'shopping', 'haushalt', 'transport', 'hobby', 'freizeit']
    description: "Alltägliche Aktivitäten"

# Speicher-Optimierung
storage:
  # Komprimierte Cluster behalten (in Tagen)
  keep_compressed_days: 30
  
  # Log-Dateien behalten (in Tagen)
  keep_logs_days: 7
  
  # Automatische Bereinigung aktivieren
  auto_cleanup: true

# Performance-Einstellungen
performance:
  # Batch-Größe für Komprimierung
  batch_size: 100
  
  # Threading für Komprimierung
  use_threading: true
  
  # Cache für Cluster-Analyse
  enable_cache: true

# Logging
logging:
  # Log-Level: DEBUG, INFO, WARNING, ERROR
  level: INFO
  
  # Log-Datei aktivieren
  enable_file_logging: true
  
  # Console-Logging
  enable_console_logging: true 